# Generated by Django 6.0.6 on 2026-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField()),
                ('object_type', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=20)),
                ('object_repr', models.CharField(max_length=200)),
                ('dashboard_uid', models.CharField(blank=True, max_length=100)),
                ('panel_id', models.PositiveIntegerField(blank=True, null=True)),
                ('annotation_text', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('grafana_response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Annotation Log',
                'verbose_name_plural': 'Annotation Logs',
                'ordering': ('-triggered_at',),
            },
        ),
    ]
